apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: LoadBalancer
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    name: http
 
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  serviceName: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana_image
        livenessProbe:
            exec:
              command:
              - /bin/ash
              - /home/livenessprobe.sh
            initialDelaySeconds: 10
            periodSeconds: 10
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
