apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
    name: http

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  serviceName: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_image
        livenessProbe:
            exec:
              command:
              - /bin/ash
              - /home/livenessprobe.sh
            initialDelaySeconds: 10
            periodSeconds: 10
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
