<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.0.4 setup script
 * Date: Tue, 23 Feb 2021 15:18:56 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: MySQL [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'MySQL';
$cfg['Servers'][$i]['host'] = 'mysql';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'Tb//Q]avwp]mTu#R^F4tJ86jx[ht!e"i';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>
